" setting
"文字コードをUFT-8に設定
set fenc=utf-8
set encoding=utf-8
" バックアップファイルを作らない
set nobackup
" スワップファイルを作らない
set noswapfile
" 編集中のファイルが変更されたら自動で読み直す
set autoread
" バッファが編集中でもその他のファイルを開けるように
set hidden
" 入力中のコマンドをステータスに表示する
set showcmd
" undoファイルを1カ所にまとめる
set undodir=C:\vim\undo


" 見た目系
" 行番号を表示
set number
" 現在の行を強調表示
set cursorline


" 行末の1文字先までカーソルを移動できるように
set virtualedit=onemore
" インデントはスマートインデント
set smartindent
" ビープ音を可視化
set visualbell
" 括弧入力時の対応する括弧を表示
set showmatch
" ステータスラインを常に表示
set laststatus=2
" コマンドラインの補完
set wildmode=list:longest
" 折り返し時に表示行単位での移動できるようにする
nnoremap j gj
nnoremap k gk
" バックスペースキーの有効化
set backspace=indent,eol,start


" Tab系
" 不可視文字を可視化(タブが「?-」と表示される)
set list listchars=tab:\?\-
" Tab文字を半角スペースにする
set expandtab
" 行頭以外のTab文字の表示幅（スペースいくつ分）
set tabstop=2
" 行頭でのTab文字の表示幅
set shiftwidth=2
" 改行時に前の行のインデントを継続する
set autoindent 
" 改行時に前の行の構文をチェックし次の行のインデントを増減する
set smartindent 


" 検索系
" 検索文字列が小文字の場合は大文字小文字を区別なく検索する
set ignorecase
" 検索文字列に大文字が含まれている場合は区別して検索する
set smartcase
" 検索文字列入力時に順次対象文字列にヒットさせる
set incsearch
" 検索時に最後まで行ったら最初に戻る
set wrapscan
" 検索語をハイライト表示


" ウィンドウの縦幅
set lines=55
" ウィンドウの横幅
set columns=180
" カラースキーム
colorscheme zenburn
" ダーク系のカラースキームを使う
set background=dark
" フォント設定
set guifont=Cica:h11

" ヤンク,カット操作によるクリップボードの操作
set clipboard=unnamed,autoselect

" 行が折り返し表示されていた場合、行単位ではなく表示行単位でカーソルを移動する
nnoremap j gj
nnoremap k gk
nnoremap <down> gj
nnoremap <up> gk

" ESCキーをCtrl+Jにマッピング
imap <c-j> <esc>
inoremap <silent> jj <ESC>
inoremap <silent> っj <ESC>

" 改行挿入時に挿入モードに移行しない([Space]+[Enter])
noremap <Space><CR> o<ESC>

"---------------------------
" Start Neobundle Settings.
"---------------------------
filetype plugin indent off
" bundleで管理するディレクトリを指定
if has('vim_starting')
  set runtimepath+=$VIM/.vim/bundle/neobundle.vim/
  " Required:
  call neobundle#begin(expand('$VIM/.vim/bundle/'))
endif
" neobundle自体をneobundleで管理
NeoBundleFetch 'Shougo/neobundle.vim'
" 以下は必要に応じて追加
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neomru.vim'
NeoBundle 'itchyny/lightline.vim'
NeoBundle 'vim-scripts/grep.vim'
NeoBundle 'plasticboy/vim-markdown'
NeoBundle 'kannokanno/previm'
NeoBundle 'tyru/open-browser.vim'

call neobundle#end()
" Required:
filetype plugin indent on
" vim起動時に未インストールのプラグインをインストールする
NeoBundleCheck

" markdown
autocmd BufNewFile,BufRead *.md set filetype=markdown
let g:previm_open_cmd = 'D:\\tmp\\GoogleChromePortable\\GoogleChromePortable.exe'

let g:previm_custom_css_path = '$VIM/markdown/font.css'
